[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "cloudinary>=1.44.1",
    "google-auth-oauthlib>=1.2.2",
    "google-auth>=2.40.3",
    "gspread>=6.2.1",
    "pandas>=2.3.2",
    "streamlit>=1.48.1",
    "google-auth-httplib2>=0.2.0",
    "google-api-python-client>=2.179.0",
]
